user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}

http {
    server {
        listen 80;
        server_name  localhost;

        root   /usr/share/nginx/html;
        index  index.html index.htm;
        include /etc/nginx/mime.types;

        gzip on;
        gzip_vary on;
        gzip_disable "MSIE [1-6]\.";
        gzip_min_length 256;
        gzip_proxied expired no-cache no-store private auth;
        gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;

      location ~* \.(png|jpg|jpeg|gif)$ {
         expires 365d;
         add_header Cache-Control "public, no-transform";
      }

     location ~* \.(js|css|pdf|html|swf)$ {
       expires 30d;
       add_header Cache-Control "public, no-transform";
      }


        location / {
            try_files $uri $uri/ /index.html;
        }

        location = /capabilities {
            proxy_pass http://api:8000/capabilities;
            proxy_set_header X-Forwarded-Host $host:443;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header Accept-Encoding "";
        }

        location /api/web/ {
            proxy_pass http://api:8000/api/web/;
            proxy_set_header X-Forwarded-Host $host:443;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header Accept-Encoding "";
	}

    }
}
